### ISSUE TITLE
Transition from convert-hex to binstring

### ISSUE THREAD

**Issue by MidnightLightning** [cryptocoinjs/btc-transaction#2]
We decided to move away from `convert-hex` and `convert-string` being separate libraries and merge them into `binstring`. This module needs to move away from `convert-hex` to `binstring`.

**Comment by jprichardson** [comment]
Forgot to close this issue. Fixed in `0.1.0`: https://github.com/cryptocoinjs/btc-transaction/releases/tag/0.1.0
